package com.mycompany.mavenproject1.cryptography;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


public class SHAEncryption {

    private static byte[] getSHA(String str) throws NoSuchAlgorithmException {
        MessageDigest md  = MessageDigest.getInstance("SHA-256");
        return md.digest(str.getBytes((StandardCharsets.UTF_8)));
    }

    private static String toHexString(byte[] hashedVal) {
        BigInteger num = new BigInteger(1, hashedVal);

        // conversion to hex string i.e. radix=16
        StringBuilder hexStr = new StringBuilder(num.toString(16));

        while (hexStr.length()<64){
            hexStr.insert(0, '0');
        }

        return hexStr.toString();
    }

    public static void main(String[] args) {
        try {
            System.out.println("Program to encode input string into HashCode generated by SHA-256 encryption algo");

            String input1 = "Hello World";
            System.out.println("Input : " + input1);
            System.out.println("Output : " + toHexString(getSHA(input1)));

            String input2 = "ROT(7)";
            System.out.println("Input : " + input2);
            System.out.println("Output : " + toHexString(getSHA(input2)));

        }catch (NoSuchAlgorithmException e){
            System.out.println(e.getMessage());
        }
    }
}
